/*
 Flowable 表名大小写修复脚本（完整版）

 问题：Linux MySQL lower_case_table_names=0 下，Flowable 查 ACT_XXX 而实际为 act_xxx，导致失败

 解决：先删除可能存在的空大写表，再将所有 act_* 小写表重命名为 ACT_* 大写（保留数据）

 覆盖表：ACT_EVT_LOG, ACT_GE_*, ACT_HI_*, ACT_ID_*, ACT_PROCDEF_INFO, ACT_RE_*, ACT_RU_*

 注意：必须用 -f 执行，部分表可能不存在会报错，-f 会继续执行其他语句

 用法：docker exec -i mysql mysql -f -u root -pTH0901th ruoyi-vue-pro < flowable-fix-table-case.sql
*/

USE `ruoyi-vue-pro`;

-- 关闭外键检查，否则 DROP 会因 act_* 表之间的外键约束失败
SET FOREIGN_KEY_CHECKS = 0;

-- ========== 第一步：删除可能由 Flowable 创建的空大写表 ==========
-- （你的真实数据在小写表中，大写表多为空或错误）
DROP TABLE IF EXISTS `ACT_EVT_LOG`;
DROP TABLE IF EXISTS `ACT_GE_BYTEARRAY`;
DROP TABLE IF EXISTS `ACT_GE_PROPERTY`;
DROP TABLE IF EXISTS `ACT_HI_ACTINST`;
DROP TABLE IF EXISTS `ACT_HI_ATTACHMENT`;
DROP TABLE IF EXISTS `ACT_HI_COMMENT`;
DROP TABLE IF EXISTS `ACT_HI_DETAIL`;
DROP TABLE IF EXISTS `ACT_HI_ENTITYLINK`;
DROP TABLE IF EXISTS `ACT_HI_IDENTITYLINK`;
DROP TABLE IF EXISTS `ACT_HI_PROCINST`;
DROP TABLE IF EXISTS `ACT_HI_TASKINST`;
DROP TABLE IF EXISTS `ACT_HI_TSK_LOG`;
DROP TABLE IF EXISTS `ACT_HI_VARINST`;
DROP TABLE IF EXISTS `ACT_ID_BYTEARRAY`;
DROP TABLE IF EXISTS `ACT_ID_GROUP`;
DROP TABLE IF EXISTS `ACT_ID_INFO`;
DROP TABLE IF EXISTS `ACT_ID_MEMBERSHIP`;
DROP TABLE IF EXISTS `ACT_ID_PRIV`;
DROP TABLE IF EXISTS `ACT_ID_PRIV_MAPPING`;
DROP TABLE IF EXISTS `ACT_ID_PROPERTY`;
DROP TABLE IF EXISTS `ACT_ID_TOKEN`;
DROP TABLE IF EXISTS `ACT_ID_USER`;
DROP TABLE IF EXISTS `ACT_PROCDEF_INFO`;
DROP TABLE IF EXISTS `ACT_RE_DEPLOYMENT`;
DROP TABLE IF EXISTS `ACT_RE_MODEL`;
DROP TABLE IF EXISTS `ACT_RE_MODEL_HISTORY`;
DROP TABLE IF EXISTS `ACT_RE_PROCDEF`;
DROP TABLE IF EXISTS `ACT_RU_ACTINST`;
DROP TABLE IF EXISTS `ACT_RU_DEADLETTER_JOB`;
DROP TABLE IF EXISTS `ACT_RU_ENTITYLINK`;
DROP TABLE IF EXISTS `ACT_RU_EVENT_SUBSCR`;
DROP TABLE IF EXISTS `ACT_RU_EXECUTION`;
DROP TABLE IF EXISTS `ACT_RU_EXTERNAL_JOB`;
DROP TABLE IF EXISTS `ACT_RU_HISTORY_JOB`;
DROP TABLE IF EXISTS `ACT_RU_IDENTITYLINK`;
DROP TABLE IF EXISTS `ACT_RU_JOB`;
DROP TABLE IF EXISTS `ACT_RU_SUSPENDED_JOB`;
DROP TABLE IF EXISTS `ACT_RU_TASK`;
DROP TABLE IF EXISTS `ACT_RU_TIMER_JOB`;
DROP TABLE IF EXISTS `ACT_RU_VARIABLE`;

-- ========== 第二步：将小写表重命名为大写（保留数据） ==========
RENAME TABLE `act_evt_log` TO `ACT_EVT_LOG`;
RENAME TABLE `act_ge_bytearray` TO `ACT_GE_BYTEARRAY`;
RENAME TABLE `act_ge_property` TO `ACT_GE_PROPERTY`;
RENAME TABLE `act_hi_actinst` TO `ACT_HI_ACTINST`;
RENAME TABLE `act_hi_attachment` TO `ACT_HI_ATTACHMENT`;
RENAME TABLE `act_hi_comment` TO `ACT_HI_COMMENT`;
RENAME TABLE `act_hi_detail` TO `ACT_HI_DETAIL`;
RENAME TABLE `act_hi_entitylink` TO `ACT_HI_ENTITYLINK`;
RENAME TABLE `act_hi_identitylink` TO `ACT_HI_IDENTITYLINK`;
RENAME TABLE `act_hi_procinst` TO `ACT_HI_PROCINST`;
RENAME TABLE `act_hi_taskinst` TO `ACT_HI_TASKINST`;
RENAME TABLE `act_hi_tsk_log` TO `ACT_HI_TSK_LOG`;
RENAME TABLE `act_hi_varinst` TO `ACT_HI_VARINST`;
RENAME TABLE `act_id_bytearray` TO `ACT_ID_BYTEARRAY`;
RENAME TABLE `act_id_group` TO `ACT_ID_GROUP`;
RENAME TABLE `act_id_info` TO `ACT_ID_INFO`;
RENAME TABLE `act_id_membership` TO `ACT_ID_MEMBERSHIP`;
RENAME TABLE `act_id_priv` TO `ACT_ID_PRIV`;
RENAME TABLE `act_id_priv_mapping` TO `ACT_ID_PRIV_MAPPING`;
RENAME TABLE `act_id_property` TO `ACT_ID_PROPERTY`;
RENAME TABLE `act_id_token` TO `ACT_ID_TOKEN`;
RENAME TABLE `act_id_user` TO `ACT_ID_USER`;
RENAME TABLE `act_procdef_info` TO `ACT_PROCDEF_INFO`;
RENAME TABLE `act_re_deployment` TO `ACT_RE_DEPLOYMENT`;
RENAME TABLE `act_re_model` TO `ACT_RE_MODEL`;
RENAME TABLE `act_re_procdef` TO `ACT_RE_PROCDEF`;
RENAME TABLE `act_ru_actinst` TO `ACT_RU_ACTINST`;
RENAME TABLE `act_ru_deadletter_job` TO `ACT_RU_DEADLETTER_JOB`;
RENAME TABLE `act_ru_entitylink` TO `ACT_RU_ENTITYLINK`;
RENAME TABLE `act_ru_event_subscr` TO `ACT_RU_EVENT_SUBSCR`;
RENAME TABLE `act_ru_execution` TO `ACT_RU_EXECUTION`;
RENAME TABLE `act_ru_external_job` TO `ACT_RU_EXTERNAL_JOB`;
RENAME TABLE `act_ru_history_job` TO `ACT_RU_HISTORY_JOB`;
RENAME TABLE `act_ru_identitylink` TO `ACT_RU_IDENTITYLINK`;
RENAME TABLE `act_ru_job` TO `ACT_RU_JOB`;
RENAME TABLE `act_ru_suspended_job` TO `ACT_RU_SUSPENDED_JOB`;
RENAME TABLE `act_ru_task` TO `ACT_RU_TASK`;
RENAME TABLE `act_ru_timer_job` TO `ACT_RU_TIMER_JOB`;
RENAME TABLE `act_ru_variable` TO `ACT_RU_VARIABLE`;

-- 恢复外键检查
SET FOREIGN_KEY_CHECKS = 1;
